Updated. Motion not done

diff --git a/sdk/target/etc/init.d/S01syslogd b/sdk/target/etc/init.d/S01syslogd
--- a/sdk/target/etc/init.d/S01syslogd
+++ b/sdk/target/etc/init.d/S01syslogd
@@ -1,35 +1,55 @@
 #!/bin/sh
 
 DAEMON="syslogd"
-DAEMON_ARGS="-n -C64 -t"
-PIDFILE="/run/$DAEMON.pid"
+PIDFILE="/var/run/$DAEMON.pid"
 
+SYSLOGD_ARGS=""
+
+# shellcheck source=/dev/null
+[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"
+
+# BusyBox' syslogd does not create a pidfile, so pass "-n" in the command line
+# and use "-m" to instruct start-stop-daemon to create one.
 start() {
-	printf 'Starting %s: ' $DAEMON
-	start-stop-daemon -q -p $PIDFILE -S -b -m -x /sbin/$DAEMON -- $DAEMON_ARGS
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+	printf 'Starting %s: ' "$DAEMON"
+	# shellcheck disable=SC2086 # we need the word splitting
+	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/sbin/$DAEMON" \
+		-- -n $SYSLOGD_ARGS
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
 }
 
 stop() {
-	printf 'Stopping %s: ' $DAEMON
-	start-stop-daemon -q -p $PIDFILE -K
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
-	rm -f $PIDFILE
+	printf 'Stopping %s: ' "$DAEMON"
+	start-stop-daemon -K -q -p "$PIDFILE"
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		rm -f "$PIDFILE"
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
+}
+
+restart() {
+	stop
+	sleep 1
+	start
 }
 
 case "$1" in
-	start | stop)
-		$1
-		;;
-	restart | reload)
-		stop
-		sleep 1
-		start
-		;;
+	start|stop|restart)
+		"$1";;
+	reload)
+		# Restart, since there is no true "reload" feature.
+		restart;;
 	*)
 		echo "Usage: $0 {start|stop|restart|reload}"
 		exit 1
-		;;
 esac
-
-exit 0
diff --git a/sdk/target/etc/init.d/S96impconfig b/sdk/target/etc/init.d/S96impconfig
--- a/sdk/target/etc/init.d/S96impconfig
+++ b/sdk/target/etc/init.d/S96impconfig
@@ -1,34 +1,48 @@
 #!/bin/sh
 
+config="/etc/imp.conf"
+
+check_imp() {
+	echo -n "Establishing connection ..."
+	i=0
+	while :; do
+		grep -q running /proc/jz/isp/isp-fs &&
+			imp-control getdeviceid > /dev/null &&
+			echo " OK" && return
+		echo -n "."
+		i=$((i + 1))
+		sleep 1
+		[ $i -gt 10 ] && echo " FAIL (timeout)" && exit 1
+	done
+}
+
 start() {
-	[ ! -f "/etc/imp.conf" ] && return
-
-	echo -n "Restoring IMP Configuration: "
-	while read -r line; do
-		imp-control $line
-	done < /etc/imp.conf
-	echo "OK"
-}
-
-stop() {
-	:
-}
-
-restart() {
-	start
-}
-
-reload() {
-	start
+	check_imp
+	echo -n "Restoring IMP Configuration:"
+	if [ -f "$config" ]; then
+		echo
+		while read -r line; do
+			echo -e " * $line"
+			imp-control $line > /dev/null
+		done < $config
+		echo "Done"
+	else
+		echo "DISABLED"
+		return
+	fi
 }
 
 case "$1" in
-	start|stop|restart|reload)
-		"$1"
+	start | restart | reload)
+		start
+		;;
+	stop)
+		:
 		;;
 	*)
 		echo "Usage: $0 {start|restart|reload}"
 		exit 1
+		;;
 esac
 
 exit 0
